### ISSUE TITLE
Possible to port to actively-maintained rgb-led-matrix by hzeller?

### ISSUE THREAD

**Issue by garrettmiller** [adafruit/Adafruit-NextBus#3]
Hi!  I was wondering it might be possible to port this library to be compatible with the actively-maintained rpi rgb-led-matrix library? 
 https://github.com/hzeller/rpi-rgb-led-matrix 

I've started some work on it, modifying what I think are the necessary declarations, but this is as far as I got.  Unfortunately I don't understand the inner workings of the rgbmatrix library well enough to know what needs to happen next:

```
user@ledboard:~/Adafruit-NextBus$ sudo python nextbus-matrix.py
Traceback (most recent call last):
  File "nextbus-matrix.py", line 186, in <module>
    matrix.SetImage(0, 0, 0)
  File "core.pyx", line 13, in rgbmatrix.core.Canvas.SetImage
AttributeError: 'int' object has no attribute 'mode'
```

**Comment by ladyada** [comment]
its probably possible - but isn't a high priority. if you get it working with the latest version please submit a PR!
